### ISSUE TITLE
Sources.jar

### ISSUE THREAD

**Issue by WellingtonCosta** [Adonai/convalida-extended#1]
Why the sources.jar is very important for you?

**Comment by Adonai** [comment]
Hi! 

* I have multiple workspaces and I don't want to download dependant stuff by hand each time.
* I don't want to re-download sources each time upstream author changes anything
* It's just common sense. Open-source project should encourage people to contribute back. There's a better chance for it if they immediately see the source code.

**Comment by WellingtonCosta** [comment]
You can clone the repository and you can execute git pull command to refresh your local files.

Yeah, I agree that open-source projects should encourage people to contribute back, but I think the contributions be the important stuffs.

Well, I would like to thank you for your contributions on my project.

Cheers!
